export interface TimezoneOption {
  value: string;
  label: string;
}

export const TIMEZONE_OPTIONS: TimezoneOption[] = [
  { value: '-12:00', label: 'UTC-12 (Baker Island, Howland Island)' },
  { value: '-11:00', label: 'UTC-11 (Niue, American Samoa)' },
  { value: '-10:00', label: 'UTC-10 (Honolulu, Papeete)' },
  { value: '-09:30', label: 'UTC-09:30 (Marquesas Islands)' },
  { value: '-09:00', label: 'UTC-09 (Anchorage, Juneau)' },
  { value: '-08:00', label: 'UTC-08 (Los Angeles, Vancouver)' },
  { value: '-07:00', label: 'UTC-07 (Denver, Phoenix)' },
  { value: '-06:00', label: 'UTC-06 (Chicago, Mexico City)' },
  { value: '-05:00', label: 'UTC-05 (New York, Toronto)' },
  { value: '-04:00', label: 'UTC-04 (Caracas, Santiago)' },
  { value: '-03:30', label: "UTC-03:30 (St. John's)" },
  { value: '-03:00', label: 'UTC-03 (Buenos Aires, São Paulo)' },
  { value: '-02:00', label: 'UTC-02 (Fernando de Noronha, South Georgia)' },
  { value: '-01:00', label: 'UTC-01 (Azores, Cape Verde)' },
  { value: '+00:00', label: 'UTC+0 (London, Lisbon)' },
  { value: '+01:00', label: 'UTC+1 (Berlin, Paris)' },
  { value: '+02:00', label: 'UTC+2 (Cairo, Johannesburg)' },
  { value: '+03:00', label: 'UTC+3 (Moscow, Istanbul)' },
  { value: '+03:30', label: 'UTC+3:30 (Tehran)' },
  { value: '+04:00', label: 'UTC+4 (Dubai, Yerevan)' },
  { value: '+04:30', label: 'UTC+4:30 (Kabul)' },
  { value: '+05:00', label: 'UTC+5 (Karachi, Tashkent)' },
  { value: '+05:30', label: 'UTC+5:30 (Mumbai, Colombo)' },
  { value: '+05:45', label: 'UTC+5:45 (Kathmandu)' },
  { value: '+06:00', label: 'UTC+6 (Dhaka, Almaty)' },
  { value: '+06:30', label: 'UTC+6:30 (Yangon)' },
  { value: '+07:00', label: 'UTC+7 (Bangkok, Jakarta)' },
  { value: '+08:00', label: 'UTC+8 (Beijing, Singapore)' },
  { value: '+08:45', label: 'UTC+8:45 (Eucla)' },
  { value: '+09:00', label: 'UTC+9 (Tokyo, Seoul)' },
  { value: '+09:30', label: 'UTC+9:30 (Adelaide, Darwin)' },
  { value: '+10:00', label: 'UTC+10 (Sydney, Brisbane)' },
  { value: '+10:30', label: 'UTC+10:30 (Lord Howe Island)' },
  { value: '+11:00', label: 'UTC+11 (Solomon Islands, Noumea)' },
  { value: '+12:00', label: 'UTC+12 (Auckland, Suva)' },
  { value: '+12:45', label: 'UTC+12:45 (Chatham Islands)' },
  { value: '+13:00', label: 'UTC+13 (Apia, Nukuʻalofa)' },
  { value: '+14:00', label: 'UTC+14 (Kiritimati, Line Islands)' },
];
